#!/usr/bin/env bash
# PreToolUse guard: block edits to genuinely generated / protected files.
# Override for an intentional edit: set PM_ALLOW_PROTECTED=1 in the environment.
#
# WHY THIS MATCHES SIGNALS, NOT PATH SHAPES
#   The first version denied a fixed glob list that included `*/dist/*`,
#   `*/build/*` and `*/src/components/ui/*`, explaining the last one as
#   "generated shadcn UI". In any repo that does not use shadcn, that path is
#   ordinary hand-written source — and a repo that commits its `dist/` (a
#   published bundle, a Go binary, a docs site) has a tracked directory, not
#   build output. So the guard blocked real work and offered a remedy
#   ("regenerate via the shadcn CLI") that did not exist there.
#
#   Each rule below now names the fact it read:
#     - lockfiles           : generated by a package manager, in every repo
#     - .yarn/releases/*    : a vendored yarn binary, in every repo that has one
#     - dist/ build/ out/   : blocked ONLY when git itself ignores the path
#     - src/components/ui/* : blocked ONLY when components.json (shadcn) exists
#     - .github/workflows/* : blocked always, with a remedy chosen from the remote
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/hook-output.sh
source "${SCRIPT_DIR}/lib/hook-output.sh"

input="$(hook_read_stdin)"
hook_detect_platform "$input"
file=$(printf '%s' "$input" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    ti = d.get('tool_input', {}) or {}
    print(ti.get('file_path', '') or ti.get('path', '') or '')
except Exception:
    print('')
" 2>/dev/null)

[ -z "$file" ] && hook_allow
[ "${PM_ALLOW_PROTECTED:-0}" = "1" ] && hook_allow

# Repo root for the file being edited — every derived check below needs it.
file_dir="$(dirname "$file")"
repo_root="$(git -C "$file_dir" rev-parse --show-toplevel 2>/dev/null || true)"

# git_ignored <path> — true when git itself says this path is ignored, i.e. it
# really is build output rather than a tracked directory that happens to be
# named dist/ or build/.
git_ignored() {
  [ -n "$repo_root" ] || return 1
  git -C "$repo_root" check-ignore -q -- "$1" 2>/dev/null
}

deny() {
  local reason="$1"
  reason="$reason If this edit is genuinely intended and the user asked for it, set PM_ALLOW_PROTECTED=1 in the environment and retry."
  echo "$reason" >&2
  hook_deny "$reason"
}

case "$file" in
  *.lock|*/package-lock.json|*/pnpm-lock.yaml|*/bun.lockb|*/go.sum)
    deny "BLOCKED: '$file' is a package-manager lockfile — it is generated, never hand-edited. Change the manifest (package.json / Cargo.toml / pyproject.toml / go.mod) and re-run the package manager so the lockfile is regenerated."
    ;;
  */.yarn/releases/*)
    deny "BLOCKED: '$file' is the vendored Yarn binary under .yarn/releases/. Change it with 'yarn set version <version>', not by editing the file."
    ;;
  */.github/workflows/*)
    remedy="Edit it through your GitHub host's API or web UI rather than the local file"
    if [ -n "$repo_root" ] && git -C "$repo_root" remote get-url origin 2>/dev/null | grep -q 'github\.com'; then
      remedy="Edit it via the GitHub MCP (create_or_update_file) if that server is configured for this session; otherwise use 'gh api' or the GitHub web UI"
    fi
    deny "BLOCKED: '$file' is a GitHub Actions workflow. $remedy."
    ;;
  */src/components/ui/*|*/components/ui/*)
    # The only honest signal that this directory is generated is a shadcn
    # config. Without it, this is hand-written source in a conventional place.
    if [ -n "$repo_root" ] && [ -f "$repo_root/components.json" ]; then
      deny "BLOCKED: '$file' sits under components/ui/ in a shadcn project (detected: $repo_root/components.json) — these files are generated. Re-generate with 'npx shadcn@latest add <component>', or move your customisation into a wrapper component outside components/ui/."
    fi
    ;;
  */dist/*|*/build/*|*/out/*|*/.next/*|*/target/debug/*|*/target/release/*)
    # Blocked only when git ignores it — a committed dist/ is a deliberate
    # artifact directory, not build output this hook should defend.
    if git_ignored "$file"; then
      deny "BLOCKED: '$file' is build output — git ignores this path in $repo_root, so it is regenerated by the build and any edit here is discarded. Change the source and re-run the build."
    fi
    ;;
esac
hook_allow
