#!/usr/bin/env bash
# PreToolUse guard: block writes to genuinely generated / protected files.
# Override for an intentional edit: set PM_ALLOW_PROTECTED=1 in the environment.
#
# WHY THIS KEYS ON THE PATH BEING WRITTEN, NOT THE TOOL DOING THE WRITING
#   Until 2026-08-31 this hook was wired to `Edit|Write|MultiEdit|…` and read a
#   `file_path` out of the payload. So it asked "is a file-editing TOOL touching
#   this path?" when the question it exists to answer is "is this path being
#   modified?". `Bash` sits between the two — `cat > f <<EOF`, `sed -i`, `tee`,
#   `cp` — and in that gap the guard's silence read as a pass. Worse, the actor
#   the guard exists to constrain is an agent, and agents have Bash: the bypass
#   was available to precisely the wrong party, by default, with no intent to
#   circumvent. An agent that simply preferred Bash never saw the guard and
#   never learned the file was protected.
#
#   The decision now runs over WRITE TARGETS, whatever produced them.
#   hooks/lib/write-targets.py parses the command and reports only operands in a
#   writing position; a protected path mentioned in a `grep` pattern, a commit
#   message or a heredoc body is never a target, so the false-positive class
#   already on record for `docker-guard.py` (which matches command text) does
#   not apply here. Where a target cannot be resolved statically the parser says
#   UNSURE and this hook surfaces that rather than falling silent — see
#   "WHAT THIS STILL CANNOT SEE" below.
#
# WHY THE RULES MATCH SIGNALS, NOT PATH SHAPES
#   The first version denied a fixed glob list that included `*/dist/*`,
#   `*/build/*` and `*/src/components/ui/*`, explaining the last one as
#   "generated shadcn UI". In any repo that does not use shadcn, that path is
#   ordinary hand-written source — and a repo that commits its `dist/` (a
#   published bundle, a Go binary, a docs site) has a tracked directory, not
#   build output. So the guard blocked real work and offered a remedy
#   ("regenerate via the shadcn CLI") that did not exist there.
#
#   Each rule below names the fact it read:
#     - lockfiles           : generated by a package manager, in every repo
#     - .yarn/releases/*    : a vendored yarn binary, in every repo that has one
#     - dist/ build/ out/   : blocked ONLY when git itself ignores the path
#     - src/components/ui/* : blocked ONLY when components.json (shadcn) exists
#     - .github/workflows/* : blocked always, with a remedy chosen from the remote
#
# WHAT THIS STILL CANNOT SEE — stated because a believed-closed gap is worse
# than a known one:
#   - Code run inside an interpreter (`python3 -c`, `node -e`, `eval`, `| sh`,
#     a heredoc piped to a shell) writes in a language this parser does not
#     read. Reported as UNSURE, never silently allowed.
#   - Targets built at runtime (`> "$OUT"`, `xargs`, `find -exec`, a glob) and
#     paths inside a patch fed to `patch`/`git apply`. Also UNSURE.
#   - Ordinary programs that happen to write (`make`, `npm install`, a checked-in
#     script). NOT reported: at that breadth the warning fires on everything and
#     means nothing, and the tool-level guard never covered them either.
#   - Metadata-only changes (`chmod`, `chown`) and git's own restores
#     (`git checkout -- f`, `git restore`), which replay tracked content rather
#     than authoring new content.
#   The half that closes those is a git/CI check on the modified path — it sees
#   the outcome rather than the mechanism, so no choice of tool routes around
#   it. This hook is the fast-feedback half, not the binding one.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/hook-output.sh
source "${SCRIPT_DIR}/lib/hook-output.sh"

input="$(hook_read_stdin)"
hook_detect_platform "$input"

[ -z "$input" ] && hook_allow
[ "${PM_ALLOW_PROTECTED:-0}" = "1" ] && hook_allow

# TARGET <tab> <abs path> <tab> <fragment>   — a file this call will write
# UNSURE <tab> <why>      <tab> <fragment>   — a write this parse cannot resolve
analysis="$(printf '%s' "$input" \
  | python3 "${SCRIPT_DIR}/lib/write-targets.py" 2>/dev/null)"

deny() {
  local reason="$1"
  reason="$reason If this edit is genuinely intended and the user asked for it, set PM_ALLOW_PROTECTED=1 in the environment and retry."
  echo "$reason" >&2
  hook_deny "$reason"
}

# classify <abs path> <fragment> <TARGET|DELETE> — deny (and exit) if protected.
classify() {
  local file="$1" via="$2" kind="$3" repo_root remedy context=""
  [ -n "$file" ] || return 0
  [ -n "$via" ] && context=" (via: $via)"

  # Repo root for the file being written — every derived check below needs it.
  repo_root="$(git -C "$(dirname "$file")" rev-parse --show-toplevel 2>/dev/null || true)"

  case "$file" in
    *.lock|*/package-lock.json|*/pnpm-lock.yaml|*/bun.lockb|*/go.sum)
      deny "BLOCKED: '$file' is a package-manager lockfile — it is generated, never hand-edited.$context Change the manifest (package.json / Cargo.toml / pyproject.toml / go.mod) and re-run the package manager so the lockfile is regenerated."
      ;;
    */.yarn/releases/*)
      deny "BLOCKED: '$file' is the vendored Yarn binary under .yarn/releases/.$context Change it with 'yarn set version <version>', not by editing the file."
      ;;
    */.github/workflows/*)
      remedy="Edit it through your GitHub host's API or web UI rather than the local file"
      if [ -n "$repo_root" ] && git -C "$repo_root" remote get-url origin 2>/dev/null | grep -q 'github\.com'; then
        remedy="Edit it via the GitHub MCP (create_or_update_file) if that server is configured for this session; otherwise use 'gh api' or the GitHub web UI"
      fi
      deny "BLOCKED: '$file' is a GitHub Actions workflow.$context $remedy."
      ;;
    */src/components/ui/*|*/components/ui/*)
      # The only honest signal that this directory is generated is a shadcn
      # config. Without it, this is hand-written source in a conventional place.
      if [ -n "$repo_root" ] && [ -f "$repo_root/components.json" ]; then
        deny "BLOCKED: '$file' sits under components/ui/ in a shadcn project (detected: $repo_root/components.json) — these files are generated.$context Re-generate with 'npx shadcn@latest add <component>', or move your customisation into a wrapper component outside components/ui/."
      fi
      ;;
    */dist/*|*/build/*|*/out/*|*/.next/*|*/target/debug/*|*/target/release/*)
      # Blocked only when git ignores it — a committed dist/ is a deliberate
      # artifact directory, not build output this hook should defend. And only
      # for content: this rule's whole argument is "your edit is discarded by
      # the next build", which is not a reason to stop `rm -rf dist/`.
      if [ "$kind" != "DELETE" ] && [ -n "$repo_root" ] && git -C "$repo_root" check-ignore -q -- "$file" 2>/dev/null; then
        deny "BLOCKED: '$file' is build output — git ignores this path in $repo_root, so it is regenerated by the build and any edit here is discarded.$context Change the source and re-run the build."
      fi
      ;;
  esac
  return 0
}

# Process substitution, not a pipe: `deny` must be able to exit THIS shell.
# In a pipeline the loop is a subshell, `exit` leaves it, and the script would
# fall through and print a second, contradictory allow.
unsure=""
while IFS=$'\t' read -r kind detail fragment; do
  case "$kind" in
    TARGET|DELETE) classify "$detail" "$fragment" "$kind" ;;
    UNSURE)        unsure="${unsure}  - ${detail}"$'\n' ;;
  esac
done < <(printf '%s\n' "$analysis")

# No silent failure path: "could not determine" must not be delivered as "no
# protected file was touched". This is advisory, never a block — the command
# still runs, and the agent is told what the guard could not check.
if [ -n "$unsure" ]; then
  hook_additional_context "PROTECTED-FILE GUARD: this command writes somewhere it could not resolve statically, so it was NOT checked against the protected-path rules:
${unsure}If it writes a lockfile, a .github/workflows/ file, .yarn/releases/, generated shadcn UI, or gitignored build output, that is on you — rewrite it with a literal path so the guard can see the target, or ask the user before proceeding."
fi

hook_allow
