#!/usr/bin/env bash
# build-opencode-agents.sh — generate .opencode/agent/*.md from agents/*.md.
#
# Usage:
#   bash scripts/build-opencode-agents.sh [repo-root] [--check]
#   bash scripts/build-opencode-agents.sh -h | --help
#
# --check regenerates into a temp dir and diffs, so CI can fail on drift
# without writing to the working tree.
#
# Why this exists: OpenCode validates agent frontmatter strictly and refuses to
# start on a bad field. A Claude Code agent file uses `tools: Read, Grep, Bash`
# (a comma string) and `model: sonnet` (no provider prefix); OpenCode wants
# `tools` as an object of tool->bool and a provider-prefixed model, and rejects
# anything else with ConfigInvalidError. So the Claude files cannot simply be
# copied — they are translated here, and the translation is committed so users
# installing from a clone need no build step.
#
# Exit 0 on success; 1 if --check finds drift.
set -euo pipefail

usage() { sed -n '2,18p' "$0" | sed 's/^#[[:space:]]\{0,1\}//'; exit "${1:-0}"; }
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then usage 0; fi

ROOT="."
CHECK=false
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=true ;;
    -*) echo "Unknown flag: $arg" >&2; exit 1 ;;
    *) ROOT="$arg" ;;
  esac
done
ROOT="$(cd "$ROOT" && pwd)"

SRC="$ROOT/agents"
DEST="$ROOT/.opencode/agent"
[[ -d "$SRC" ]] || { echo "No agents/ directory — nothing to build"; exit 0; }

if [[ "$CHECK" == true ]]; then
  DEST="$(mktemp -d)"
  trap 'rm -rf "$DEST"' EXIT
fi
mkdir -p "$DEST"

# Claude model aliases -> OpenCode provider-prefixed model ids.
map_model() {
  case "$1" in
    sonnet)  echo "anthropic/claude-sonnet-4-6" ;;
    opus)    echo "anthropic/claude-opus-4-1" ;;
    haiku)   echo "anthropic/claude-haiku-4-5" ;;
    ""|inherit) echo "" ;;
    *)       echo "$1" ;;   # already provider-prefixed, or an explicit id
  esac
}

count=0
for f in "$SRC"/*.md; do
  [[ -e "$f" ]] || continue
  base="$(basename "$f")"

  name=$(sed -n 's/^name:[[:space:]]*//p' "$f" | head -1)
  desc=$(sed -n 's/^description:[[:space:]]*//p' "$f" | head -1)
  tools=$(sed -n 's/^tools:[[:space:]]*//p' "$f" | head -1)
  model=$(sed -n 's/^model:[[:space:]]*//p' "$f" | head -1)
  [[ -n "$name" ]] || name="${base%.md}"

  # Body = everything after the closing --- of the frontmatter.
  body_start=$(awk 'NR>1 && /^---[[:space:]]*$/ {print NR+1; exit}' "$f")
  [[ -n "$body_start" ]] || body_start=1

  {
    echo "---"
    echo "name: $name"
    [[ -n "$desc" ]] && echo "description: $desc"
    echo "mode: subagent"
    oc_model=$(map_model "$model")
    [[ -n "$oc_model" ]] && echo "model: $oc_model"
    if [[ -n "$tools" ]]; then
      # `Read, Grep, Glob, Bash` -> an object of lowercased tool -> true.
      echo "tools:"
      echo "$tools" | tr ',' '\n' | while read -r t; do
        t="$(echo "$t" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')"
        [[ -n "$t" ]] && echo "  $t: true"
      done
    fi
    echo "---"
    echo
    echo "<!-- Generated by scripts/build-opencode-agents.sh from agents/$base — do not edit directly. -->"
    echo
    tail -n "+$body_start" "$f"
  } > "$DEST/$base"
  count=$((count + 1))
done

if [[ "$CHECK" == true ]]; then
  if ! diff -r -q "$ROOT/.opencode/agent" "$DEST" >/dev/null 2>&1; then
    echo "ERROR: .opencode/agent/ is out of sync with agents/ — run: make opencode-agents" >&2
    diff -r "$ROOT/.opencode/agent" "$DEST" >&2 || true
    exit 1
  fi
  echo "OpenCode agent adapters in sync ($count agent(s))"
  exit 0
fi

echo "Generated $count OpenCode agent adapter(s) in .opencode/agent/"
